### ISSUE TITLE
renew refreshtoken?

### ISSUE THREAD

**Issue by tailon222** [3urobeat/steam-idler#12]
Hi!, i have a question about how to renew refreshtoken so we have it forever.

I don't really know how it works because i haven't had my idle for more than 200 days, but i think the script once the token expires we have to put the steam guard code again in every account right?  i just saw a function in the steam-session modules that can help renew that, or maybe i understood wrong?  is called    `renewRefreshToken()`  here is the link:
https://github.com/DoctorMcKay/node-steam-session#renewrefreshtoken

I guess the idea is to check the expiration date and if there is about 3 days left until it expires, create a new token with that function?

**Comment by tailon222** [comment]
Thank you for the response! take as much time as you need :)

**Comment by 3urobeat** [comment]
After some experimenting a few weeks ago, steam-session's `renewRefreshToken()` does seem to work.  
However steam-user v5, which came out a bit later, has an automatic `renewRefreshTokens` feature now.  
I haven't been able to test if it works as expected (because I can't trigger a manual refresh with it) but I'd expect it to. I have enabled it and I guess we will see how it pans out.  

I'll leave this issue open until version 1.9 is out.

**Comment by 3urobeat** [comment]
Version 1.9 is now finally out which includes this feature.  
You can read the full changelog [here](https://github.com/3urobeat/steam-idler/releases/tag/1.9)
